Add support for phpspec ^6.1
akeneo/PhpSpecSkipExampleExtension pull request #22
Opened 2019-12-09 19:30 UTC by dannyvw

2020-01-02 19:15 UTC, Nyholm commented
Maybe we should stop testing on PHP 7.1 and include PHP7.4 instead?

2020-07-01 22:57 UTC, GrahamCampbell commented
> Maybe we should stop testing on PHP 7.1 and include PHP7.4 instead?

Only if 5 is actually going to be dropped, rather than going with my suggestion of `^5.0|^6.0` for the version.

2020-07-01 22:57 UTC, GrahamCampbell commented on composer.json
> +        "phpspec/phpspec": "^6.1"
I think this should be `^5.0|^6.0`. Why drop 5? If we are going to drop 5, then we probably want another major release, like in the past.

2020-07-01 22:57 UTC, GrahamCampbell requested changes
See comments.

2021-12-09 19:09 UTC, dannyvw commented
See https://github.com/akeneo/PhpSpecSkipExampleExtension/pull/23

2021-12-09 19:09 UTC, closed without merging